insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Allene Reboul', '6 Caliangt Drive', '1997-12-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Skell Kennicott', '1407 Superior Crossing', '1992-02-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Luci Crosgrove', '84479 Hooker Lane', '2000-01-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Pauli Boas', '871 Express Lane', '2000-11-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kermit Erat', '054 Roxbury Drive', '1996-12-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Amandi Davidsohn', '3 Monica Junction', '2003-03-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jorgan Dunseath', '2980 Mccormick Terrace', '2001-12-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Maurice Prigg', '721 Schlimgen Point', '1994-09-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bone Darlison', '6 Hovde Lane', '2000-02-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nancey Peter', '65001 Clyde Gallagher Hill', '1996-01-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kore Suthren', '00272 Scofield Hill', '1996-11-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Fairleigh Evenden', '1 Southridge Parkway', '1999-01-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gerhardt Lortz', '26212 Homewood Center', '2000-07-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Stepha Seivertsen', '99565 Trailsway Junction', '2000-02-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Doe Reary', '33791 Maywood Parkway', '1992-05-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rheba Crisell', '02870 Mallard Terrace', '1994-07-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hayden Cristou', '4087 Killdeer Way', '1993-09-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Morgun Tyght', '3 Glendale Lane', '1995-12-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kile Gisburne', '4329 Kings Pass', '1995-02-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ly Dmitrienko', '83448 Heffernan Road', '1993-04-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Thane Blague', '7928 Annamark Drive', '1997-12-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Janina Tommasetti', '36 Magdeline Center', '1999-01-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Carmelle Stoter', '4 Randy Trail', '1994-04-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Allard Pusill', '6 Lerdahl Place', '2003-08-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Clemmy Sapey', '04433 Dunning Circle', '1998-03-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Onida Morcomb', '237 Hooker Place', '1993-01-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lorrie Nicholls', '8071 Anthes Center', '1998-08-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Angelique Campany', '1251 Orin Point', '1992-04-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dehlia Abelovitz', '0 Sheridan Hill', '1999-08-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lela Isabell', '9 Mcguire Hill', '1992-12-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Clemence Crossingham', '0841 Basil Alley', '1993-07-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Chane Simonato', '8521 Luster Crossing', '1994-11-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Allis Grishunin', '5 Fairview Terrace', '1998-07-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gabi Mackilpatrick', '9 Comanche Plaza', '2004-07-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sergent Boddice', '3321 Eagle Crest Circle', '1996-02-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tybalt Battrick', '60829 Forster Junction', '1996-12-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nerty Dockray', '530 Oriole Avenue', '1993-10-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Britteny Greves', '75 Arizona Way', '2001-09-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jennica Beels', '13576 Annamark Circle', '1996-05-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Babette Ilyin', '43098 East Pass', '2002-10-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gaspar D''Angeli', '67 Dorton Avenue', '2000-01-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nathaniel Rann', '13208 Springs Place', '1992-12-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Modestine Monro', '447 Kropf Way', '1992-11-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tore Cadding', '44 Surrey Alley', '1999-10-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Derril Beardsworth', '94024 Del Sol Trail', '2003-05-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Franny Coiley', '64986 Annamark Terrace', '1995-11-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Calv Lever', '801 Starling Pass', '1996-08-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Margy Tinman', '7 Glacier Hill Road', '1993-06-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Isador Speake', '55081 Express Circle', '1994-09-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Laetitia Meekings', '383 Talmadge Road', '2003-06-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Caril Snelman', '23 Vidon Center', '2002-03-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Addy Maile', '93067 East Alley', '1996-10-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Deidre Borsnall', '5 Dayton Court', '1992-07-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Francisco Millom', '19 Meadow Ridge Trail', '2001-04-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Claresta Latty', '92 Ridge Oak Lane', '2002-01-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bat Brice', '1223 Sundown Lane', '1995-02-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tracey Capron', '4 Moose Drive', '2004-09-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Con Pratley', '8439 Forster Point', '2001-05-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Chere Ebbens', '93936 Mcbride Avenue', '1997-09-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Pepe Climpson', '1 Michigan Junction', '1992-12-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gilli Duffin', '66224 Village Green Court', '2001-08-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Donna Bouch', '08672 Anhalt Point', '1999-09-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Mariette Monkman', '1 Sommers Crossing', '2001-08-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lauren Bagworth', '9298 Upham Street', '2004-12-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hermie Macy', '3 Pankratz Circle', '1994-05-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Fredra Toovey', '6 Riverside Center', '1994-09-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gavra Fallowes', '8299 Scoville Alley', '1993-05-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kimbra Takle', '15 Marcy Pass', '2001-11-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Stephannie Tomczykiewicz', '82390 Towne Circle', '2000-04-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Abey Emloch', '0773 Graceland Junction', '1995-09-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ira Culverhouse', '4 Boyd Circle', '1999-07-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Torie Hrihorovich', '69996 Northridge Crossing', '1992-06-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Yorke Calderon', '1203 Oxford Plaza', '2000-01-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Stephana Sprigin', '4583 Harper Plaza', '1996-08-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Montgomery Gytesham', '56187 Miller Street', '1999-10-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cate Caught', '85520 Spohn Parkway', '1994-10-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sari Roiz', '0245 Moose Center', '1993-07-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Yasmeen Winkle', '7024 Hermina Street', '2002-06-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Maxie Hamberston', '84 Alpine Plaza', '1992-10-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sinclare Dowderswell', '7 Randy Place', '2001-12-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Matilde Lecount', '1 Bultman Hill', '2000-11-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Raymond Ferrone', '5 Forest Place', '1994-02-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Valentin Waddie', '3 Fallview Avenue', '1994-06-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Electra Fawdrey', '62069 Independence Alley', '1994-07-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Odey Tregonna', '67295 Blackbird Trail', '2001-08-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gianni Bouldstridge', '495 Hansons Circle', '1999-07-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Davina Pennycook', '30 Magdeline Parkway', '2004-08-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jorrie Wackley', '3 West Plaza', '1998-09-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ansell Purseglove', '8 Bartelt Street', '1993-03-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Doretta Goodlake', '112 Red Cloud Junction', '2002-10-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Arabelle Wasbrough', '7274 Northport Center', '2004-07-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gwyneth Chestnutt', '98035 Merrick Terrace', '2000-02-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Allan Cleare', '8189 Dapin Way', '2001-05-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Iago Gourlie', '50 Susan Street', '1999-09-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Maye Whitty', '95 Di Loreto Park', '1998-10-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Vance Hast', '799 Rowland Park', '1999-05-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Richmound Eastes', '3 David Plaza', '1997-05-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Elwyn Brinkworth', '44 Mcbride Terrace', '2004-10-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Manda Whiteoak', '7 Golden Leaf Court', '2000-02-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rianon Casetta', '41127 Pierstorff Center', '2004-03-11');
