insert into tren (modelo, capacidad) values ('S10', 147);
insert into tren (modelo, capacidad) values ('Silverado 1500', 133);
insert into tren (modelo, capacidad) values ('Yukon', 138);
insert into tren (modelo, capacidad) values ('323', 123);
insert into tren (modelo, capacidad) values ('Tundra', 106);
insert into tren (modelo, capacidad) values ('Armada', 126);
insert into tren (modelo, capacidad) values ('4000s', 125);
insert into tren (modelo, capacidad) values ('Daytona', 129);
insert into tren (modelo, capacidad) values ('LS', 144);
insert into tren (modelo, capacidad) values ('Suburban 1500', 143);
insert into tren (modelo, capacidad) values ('Estate', 102);
insert into tren (modelo, capacidad) values ('SRX', 147);
insert into tren (modelo, capacidad) values ('Th!nk', 109);
insert into tren (modelo, capacidad) values ('Ram Van 3500', 148);
insert into tren (modelo, capacidad) values ('SRX', 130);
insert into tren (modelo, capacidad) values ('Sequoia', 133);
insert into tren (modelo, capacidad) values ('TL', 144);
insert into tren (modelo, capacidad) values ('2e', 143);
insert into tren (modelo, capacidad) values ('TSX', 129);
insert into tren (modelo, capacidad) values ('Yukon Denali', 116);
insert into tren (modelo, capacidad) values ('Sportage', 141);
insert into tren (modelo, capacidad) values ('Highlander', 119);
insert into tren (modelo, capacidad) values ('2500', 108);
insert into tren (modelo, capacidad) values ('X5 M', 136);
insert into tren (modelo, capacidad) values ('SLK-Class', 140);
insert into tren (modelo, capacidad) values ('Protege', 112);
insert into tren (modelo, capacidad) values ('Sentra', 144);
insert into tren (modelo, capacidad) values ('Camry', 109);
insert into tren (modelo, capacidad) values ('Prelude', 119);
insert into tren (modelo, capacidad) values ('SL-Class', 131);
insert into tren (modelo, capacidad) values ('EXP', 116);
insert into tren (modelo, capacidad) values ('Jetta', 120);
insert into tren (modelo, capacidad) values ('S10', 138);
insert into tren (modelo, capacidad) values ('Tribute', 117);
insert into tren (modelo, capacidad) values ('Canyon', 135);
insert into tren (modelo, capacidad) values ('Virage', 121);
insert into tren (modelo, capacidad) values ('Rabbit', 147);
insert into tren (modelo, capacidad) values ('Lucerne', 140);
insert into tren (modelo, capacidad) values ('Firebird', 108);
insert into tren (modelo, capacidad) values ('1500 Club Coupe', 133);
insert into tren (modelo, capacidad) values ('ES', 126);
insert into tren (modelo, capacidad) values ('E-Class', 135);
insert into tren (modelo, capacidad) values ('5000S', 131);
insert into tren (modelo, capacidad) values ('Sprinter 3500', 130);
insert into tren (modelo, capacidad) values ('SC', 117);
insert into tren (modelo, capacidad) values ('Villager', 107);
insert into tren (modelo, capacidad) values ('Cayman', 144);
insert into tren (modelo, capacidad) values ('Paseo', 117);
insert into tren (modelo, capacidad) values ('Laser', 131);
insert into tren (modelo, capacidad) values ('Frontier', 117);
insert into tren (modelo, capacidad) values ('Q7', 122);
insert into tren (modelo, capacidad) values ('Grand Voyager', 102);
insert into tren (modelo, capacidad) values ('M5', 118);
insert into tren (modelo, capacidad) values ('Ram 1500', 103);
insert into tren (modelo, capacidad) values ('Hombre', 109);
insert into tren (modelo, capacidad) values ('S-Class', 133);
insert into tren (modelo, capacidad) values ('Savana 3500', 125);
insert into tren (modelo, capacidad) values ('Bonneville', 143);
insert into tren (modelo, capacidad) values ('Montero', 138);
insert into tren (modelo, capacidad) values ('Liberty', 135);
insert into tren (modelo, capacidad) values ('V70', 109);
insert into tren (modelo, capacidad) values ('F430', 145);
insert into tren (modelo, capacidad) values ('W201', 118);
insert into tren (modelo, capacidad) values ('Starion', 107);
insert into tren (modelo, capacidad) values ('Daewoo Lacetti', 134);
insert into tren (modelo, capacidad) values ('Esprit', 118);
insert into tren (modelo, capacidad) values ('Swift', 113);
insert into tren (modelo, capacidad) values ('Sunfire', 125);
insert into tren (modelo, capacidad) values ('Grand Voyager', 126);
insert into tren (modelo, capacidad) values ('A5', 149);
insert into tren (modelo, capacidad) values ('H1', 150);
insert into tren (modelo, capacidad) values ('Xterra', 120);
insert into tren (modelo, capacidad) values ('GS', 129);
insert into tren (modelo, capacidad) values ('Tribute', 130);
insert into tren (modelo, capacidad) values ('Familia', 142);
insert into tren (modelo, capacidad) values ('CR-V', 148);
insert into tren (modelo, capacidad) values ('Envoy XL', 104);
insert into tren (modelo, capacidad) values ('Villager', 106);
insert into tren (modelo, capacidad) values ('M6', 107);
insert into tren (modelo, capacidad) values ('LX', 141);
insert into tren (modelo, capacidad) values ('Sable', 116);
insert into tren (modelo, capacidad) values ('Bonneville', 107);
insert into tren (modelo, capacidad) values ('Q', 142);
insert into tren (modelo, capacidad) values ('Sierra 1500', 141);
insert into tren (modelo, capacidad) values ('Parisienne', 123);
insert into tren (modelo, capacidad) values ('Mustang', 136);
insert into tren (modelo, capacidad) values ('Astro', 124);
insert into tren (modelo, capacidad) values ('Tahoe', 108);
insert into tren (modelo, capacidad) values ('B-Series', 130);
insert into tren (modelo, capacidad) values ('750', 150);
insert into tren (modelo, capacidad) values ('Chariot', 142);
insert into tren (modelo, capacidad) values ('S-Type', 108);
insert into tren (modelo, capacidad) values ('TSX', 103);
insert into tren (modelo, capacidad) values ('GTI', 117);
insert into tren (modelo, capacidad) values ('Spirit', 138);
insert into tren (modelo, capacidad) values ('Probe', 116);
insert into tren (modelo, capacidad) values ('3500 Club Coupe', 146);
insert into tren (modelo, capacidad) values ('Astro', 116);
insert into tren (modelo, capacidad) values ('Legend', 108);
insert into tren (modelo, capacidad) values ('Express 3500', 124);
